import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactLenis } from '../lenis/Lenis'
import ScrollProgress from "@/scrollprogress/ScrollProgress";
import Header from "@/header/Header";
import Footer from "@/footer/Footer";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Elite Black Cars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="M_wYaV_WQaXzDlBStbdhT2zr_kFrQ_wGZOwQekhF_Ck" />
      <link rel="icon" type="image/png" href="/images/Logo_main1.svg" />
      </head>
      <ReactLenis root>
        <body
          className={`${dmSans.variable} antialiased`}
        >      <Header />

          <ScrollProgress />
          {children}
          <Footer />
        </body>
      </ReactLenis>
    </html>
  );
}
